# Pytorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.5.1+cu121


## Introduction to Tensors

### Creating Tensors

In [2]:
# 1 Scalars
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# get tensor back as a python int
scalar.item()

7

In [5]:
# vector
vector = torch.tensor([7 ,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
Matrix = torch.tensor([[7,8],
                        [9, 10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
Matrix.ndim

2

In [10]:
Matrix[0], Matrix[1]

(tensor([7, 8]), tensor([ 9, 10]))

In [11]:
Matrix.shape

torch.Size([2, 2])

In [12]:
# Tensor
TENSOR = torch.tensor([[[1 ,2 ,3],
                       [3, 4, 5,],
                       [3, 6, 9]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [3, 6, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [3, 6, 9]])

### Random Tensor

Why random tensors

Random tensors are important because the way neural network learns is to start with tensors full of random and then adjust those random numbers to better represent the data

In [16]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1150, 0.5975, 0.3196, 0.3612],
        [0.2194, 0.2653, 0.2880, 0.6474],
        [0.9284, 0.3818, 0.2534, 0.6539]])

In [17]:
random_tensor.ndim

2

In [18]:
# create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size = (224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [19]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# create a tensor of all ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [22]:
# use torch.arange
one_to_ten = torch.arange(1,10)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
#creating tensors-like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Data Types

**Note:** Tensor Data types is of th three big errors you'll run into with Pytorch and deep learning. Thoes errors are:

1. Tensors of wrong datatype
2. Tensors of wrong shape
3. Tensors on the wrong device

In [24]:
float_32_tensor = torch.tensor([3.0 , 6.0, 9.0],
                               dtype=None,
                               device = None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [25]:
float_32_tensor.dtype

torch.float32

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
int_32_tensor = torch.tensor([3,6,9,], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [28]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from Tensors

In [29]:
# create tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8420, 0.7678, 0.9698, 0.6270],
        [0.0630, 0.3544, 0.5951, 0.8865],
        [0.5448, 0.0020, 0.3683, 0.2142]])

In [30]:
# find out details about some_tensor
print(some_tensor,'\n')
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'shape of tensor: {some_tensor.size()}')
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.8420, 0.7678, 0.9698, 0.6270],
        [0.0630, 0.3544, 0.5951, 0.8865],
        [0.5448, 0.0020, 0.3683, 0.2142]]) 

Datatype of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors - Tensor Operations

Tensor Operations include:
* Addition
* Subtraction
* Division
* Multiplication - Element wise
* Matrix Multiplication

In [31]:
# create a tensor and add 10
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [32]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [33]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [34]:
# Try out Pytorch in built functions
torch.mul(tensor, 10) # multiply tensor by 10

tensor([10, 20, 30])

### Matrix Multiplication

There are two of doing multiplication in deep learning

1. Element wise multiplication
2. Matrix multiplication

There are wo rules that must be followed when doing Matrix Multiplication

1. The **inner dimensions** must match
2. The resulting matrix has the outer dimensios

In [35]:
# Element wise multiplication
print(tensor, '*', tensor)
tensor * tensor

tensor([1, 2, 3]) * tensor([1, 2, 3])


tensor([1, 4, 9])

In [36]:
# Matrix Multiplcation
torch.matmul(tensor, tensor)

tensor(14)

### One of the most common errors in deep Learing is Shape Error



In [37]:
# Shapes of matrix multiplications
tensor_a = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_b = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])



In [38]:
tensor_a.shape, tensor_b.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [39]:
# torch.matmul(tensor_a, tensor_b)

We can change the shape of one of the tensors by transposing it

In [40]:
tensor_b, tensor_b.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [41]:
tensor_b.T, tensor_b.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [42]:
# the matrix multiplication works when using the transpose of tensor b

print(f'Original shape of tensor a: {tensor_a.shape}, tensor b: {tensor_b.shape}')
print(f'New shape: tensor A: {tensor_a.shape}, tensor b transpose: {tensor_b.T.shape}')
print(f'Multiplying {tensor_a.shape} @ {tensor_b.T.shape} <- inner dimension must match')
print(f'Output:\n')

output = torch.matmul(tensor_a, tensor_b.T)

print(output)
print(f'Output shape: {output.shape}')



Original shape of tensor a: torch.Size([3, 2]), tensor b: torch.Size([3, 2])
New shape: tensor A: torch.Size([3, 2]), tensor b transpose: torch.Size([2, 3])
Multiplying torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimension must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Output shape: torch.Size([3, 3])


### Tensor Aggregegation: Min, Max, Mean, Sum

In [43]:
# create tensor
x = torch.arange(1,100,10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [44]:
# find the min
x.min(), torch.min(x)

(tensor(1), tensor(1))

In [45]:
# find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [46]:
# find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [47]:
# find the sum
x.sum(), torch.sum(x)

(tensor(460), tensor(460))

### Finding the Positional Min or Max of a tensor

In [48]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [49]:
x.argmin()

tensor(0)

In [50]:
x.argmax()

tensor(9)

## Reshaping, Stacking, Sqeezing and Unsqeezing

* Reshaping - reshape an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other v - stack or side by side h - stack
* Sqeeze - removes all `1` dimensions from a tensor
* Unsqeeze - adds a `1` dimension to a tensor
* Permuute - return a view of the input with dimensions permuted (swapped in a cerain way)

In [51]:
# create tensor
x = torch.arange(1. , 10)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [52]:
# add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [53]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

Changing z, changes x because a view of a tensor shares the same memory as the original input

In [54]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [55]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [56]:
# use torch.sqeeze() - removes all 1 dims from a tensor
print(f'Previous tensor: {x_reshaped}')
print(f'Previous shape: {x_reshaped.shape}')

# remove extra dimensions
x_sqeezed = x_reshaped.squeeze()
print(f'\nNew tennsor: {x_sqeezed}')
print(f'new shape: {x_sqeezed.shape}')

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tennsor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
new shape: torch.Size([9])


In [57]:
# torch.unsqeeze() - adds a single dimension to a target tensor
print(f'previous target: {x_sqeezed}')
print(f'previous shape: {x_sqeezed.shape}')

# add an extra dimensions
x_unsqeezed = x_sqeezed.unsqueeze(dim=0)
print(f'\nNew tennsor: {x_unsqeezed}')
print(f'new shape: {x_unsqeezed.shape}')

previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape: torch.Size([9])

New tennsor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
new shape: torch.Size([1, 9])


In [58]:
# torch.permute - rearranges the dimensions of a tensor in a specified order
x_original = torch.rand(size = (224,224,3)) # (width, height , channel)

# permute the original tensor to rearrange the aixs (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2 and 2->0

print(f'previous shape: {x_original.shape}')
print(f'new shape: {x_permuted.shape}')

previous shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


## Indexign (Selecting Data)

In [59]:
# create a tensor
x = torch.arange(1, 10).reshape(1,3,3,)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [60]:
# index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [61]:
# let's index on the middle bracket
x[0, 0 ], x[0][0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [62]:
# index on the inner most bracket
x[0][0][0]

tensor(1)

In [63]:
# use the ':' to select all of a target dim
x[:, 0]

tensor([[1, 2, 3]])

In [64]:
# get all of the values of the 0th and 1 st dim but only index 1 of the 2nd dim
x[:, :, 1]

tensor([[2, 5, 8]])

In [65]:
# get all values from the 0th dim but only the 1 index value of the 1st and 2nd dim
x[:, 1, 1]

tensor([5])

In [66]:
# get index 0 of the 0th dim and all values of 2nd dim
x[0,0,:]

tensor([1, 2, 3])

## PyTorch Tensors and NumPy

NumPy is a popular Python numerical computing library

PyTorch has functionality to interact wth NumPy

* Numpy array to torch tensor -> `torch.from_numpy(ndarry)`

* torch tensor to ndarray -> `torch.Tensor.numpy()`

In [67]:
# Numpy array to torch tensor
array = np.arange(1., 8.)
tensor = torch.from_numpy(array)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [68]:
# change the value of array
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [69]:
# Tesnsor to aray
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [70]:
# change the tensor what happens to the array
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproduceability - Trying to take the randomness out out random

To reduce the randomness of neural networks and Pytorch comes a random seed.

What a random seed does is to flavour the randomness

In [71]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A, '\n')
print(random_tensor_B, '\n')
print(random_tensor_A == random_tensor_B)

tensor([[0.8674, 0.8370, 0.0502, 0.2752],
        [0.0331, 0.5698, 0.3018, 0.9819],
        [0.4384, 0.5646, 0.6069, 0.0934]]) 

tensor([[0.4729, 0.3234, 0.6060, 0.3012],
        [0.8920, 0.3844, 0.6736, 0.3512],
        [0.0476, 0.8858, 0.0267, 0.3482]]) 

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [72]:
# let's make some random but reproduceable tensors

# set seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C, '\n')
print(random_tensor_D, '\n')
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) 

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) 

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Runiing tensors on a GPU

### Getting a GPU

1. Use Google Colab
2. Use your local GPU - requires more setup
3. Use cloud computing - AWS, Azure

For 2,3 Pytorch + GPU takes some setup. Refer to the Pytorch Setup gude

### Check GPU access

In [73]:
torch.cuda.is_available()

True

In [74]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [75]:
# count the number of gpus
torch.cuda.device_count()

1

### Putting Tensors and Models on the GPU

Using a GPU results in faster calculations

In [79]:
# create a tensor (default on CPU)
tensor = torch.tensor([1,2,3])

#tensor not on gpu
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [80]:
# move tensor to gpu if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moing Tensor back to CPU

In [81]:
# if tensor is on GPU can't transfrom to numpy
# tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [82]:
# to fix the issue of not being able to convert a tensor on a GPU
# not working with numpy, put the tensor on the CPU

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])